# Production Netlify Configuration for ChooseMyPower.org
# Enterprise-grade deployment with performance optimization

[build]
  publish = "dist"
  command = "npm run build:production"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.5.0"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "production"
  ASTRO_TELEMETRY_DISABLED = "1"
  # Build optimization
  MAX_CITIES = "881"
  BATCH_SIZE = "10"
  BATCH_DELAY_MS = "2000"
  USE_CACHED_DATA = "true"

# Production Build Processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Headers for Security and Performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-Robots-Tag = "index, follow"
    
    # Performance Headers
    X-DNS-Prefetch-Control = "on"
    
    # Content Security Policy - Updated with zip-lookup.js script hash
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'sha256-XmZo4WEt88o6NwOglhSsOQi/8ldKfXqQEqahwl8DjIo=' 'sha256-UeBNPAjvA0GlAQOzFWmkpIOz4BCkTv1pRdzT/VaOX20=' 'sha256-C+N7h4sk8zBJ58VFz6N2gMzW3zlhy0CF64n+tOAWNX8=' 'sha256-0dVLqlfeNHNaV/61JLpr7IeTCwGx14lLkb6LH+i645Y=' 'sha256-gsRdXeo9pwA6MUWu95gzpKavBN/sRKvKRpF0jbzUj6k=' https://www.googletagmanager.com https://www.google-analytics.com https://vercel.live; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com data:; img-src 'self' data: https: blob:; connect-src 'self' https://api.comparepower.com https://pricing.api.comparepower.com https://www.google-analytics.com https://vitals.vercel-insights.com wss:; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self'; manifest-src 'self'; worker-src 'self'; frame-ancestors 'none'; upgrade-insecure-requests"

# Static Assets Caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

# Astro Build Assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/_astro/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/_astro/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# HTML Caching with Validation
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    Vary = "Accept-Encoding"

# Faceted Navigation Pages
[[headers]]
  for = "/electricity-plans/*"
  [headers.values]
    Cache-Control = "public, max-age=14400, s-maxage=14400"
    Vary = "Accept-Encoding"
    X-Page-Type = "faceted-navigation"

# City Pages
[[headers]]
  for = "/texas/*"
  [headers.values]
    Cache-Control = "public, max-age=21600, s-maxage=21600"
    Vary = "Accept-Encoding"
    X-Page-Type = "city-page"

# API Caching
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=600, s-maxage=600"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Sitemaps
[[headers]]
  for = "*.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/xml"

[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/xml"

# Robots.txt
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "text/plain"

# HTTPS Redirects
[[redirects]]
  from = "http://choosemypower.org/*"
  to = "https://choosemypower.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.choosemypower.org/*"
  to = "https://choosemypower.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.choosemypower.org/*"
  to = "https://choosemypower.org/:splat"
  status = 301
  force = true

# SEO-Friendly Redirects
[[redirects]]
  from = "/electricity-plans/dallas"
  to = "/electricity-plans/dallas-tx"
  status = 301

[[redirects]]
  from = "/electricity-plans/houston"
  to = "/electricity-plans/houston-tx"
  status = 301

[[redirects]]
  from = "/electricity-plans/austin"
  to = "/electricity-plans/austin-tx"
  status = 301

# API Proxy (if needed)
[[redirects]]
  from = "/api/plans/*"
  to = "https://api.comparepower.com/api/plans/:splat"
  status = 200
  headers = {X-From = "Netlify"}

# Health Check Endpoint
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# CSP Report Endpoint
[[redirects]]
  from = "/csp-report"
  to = "/.netlify/functions/csp-report"
  status = 200

# Legacy URL Redirects
[[redirects]]
  from = "/compare-electricity-plans/*"
  to = "/electricity-plans/:splat"
  status = 301

[[redirects]]
  from = "/texas-electricity-plans/*"
  to = "/electricity-plans/:splat"
  status = 301

# Specific fallback for API routes only - DO NOT use catch-all to avoid masking 404s
# The catch-all redirect was causing ZIP code navigation issues by masking legitimate 404s
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Edge Functions Configuration
[functions]
  external_node_modules = ["@netlify/neon", "drizzle-orm", "postgres"]

# Build Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    audit_url = "/"
    thresholds = { performance = 0.9, accessibility = 0.9, "best-practices" = 0.9, seo = 0.95 }
    output_path = "lighthouse-report.html"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://choosemypower.org"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing"
    ]

# Context-specific configurations
[context.production.environment]
  NODE_ENV = "production"
  ASTRO_TELEMETRY_DISABLED = "1"
  ENABLE_ANALYTICS = "true"
  ENABLE_MONITORING = "true"

[context.deploy-preview.environment]
  NODE_ENV = "staging"
  ASTRO_TELEMETRY_DISABLED = "1"
  MAX_CITIES = "50"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  ASTRO_TELEMETRY_DISABLED = "1"
  MAX_CITIES = "10"

# URL Redirects - 301 redirects for SEO preservation after removing -tx suffixes
# Major Texas Cities
[[redirects]]
  from = "/texas/dallas-tx"
  to = "/texas/dallas"
  status = 301

[[redirects]]
  from = "/texas/houston-tx" 
  to = "/texas/houston"
  status = 301

[[redirects]]
  from = "/texas/austin-tx"
  to = "/texas/austin"
  status = 301

[[redirects]]
  from = "/texas/san-antonio-tx"
  to = "/texas/san-antonio"
  status = 301

[[redirects]]
  from = "/electricity-plans/dallas-tx"
  to = "/electricity-plans/dallas"
  status = 301

[[redirects]]
  from = "/electricity-plans/houston-tx"
  to = "/electricity-plans/houston"
  status = 301

[[redirects]]
  from = "/electricity-plans/austin-tx"
  to = "/electricity-plans/austin"
  status = 301

[[redirects]]
  from = "/electricity-plans/san-antonio-tx"
  to = "/electricity-plans/san-antonio"
  status = 301

# Pattern-based redirects for all other cities
[[redirects]]
  from = "/texas/*-tx"
  to = "/texas/:splat"
  status = 301

[[redirects]]
  from = "/texas/*-tx/*"
  to = "/texas/:splat/*"
  status = 301

[[redirects]]
  from = "/electricity-plans/*-tx"
  to = "/electricity-plans/:splat"
  status = 301

[[redirects]]
  from = "/electricity-plans/*-tx/*"
  to = "/electricity-plans/:splat/*"
  status = 301

# Normalize trailing slashes for dynamic routes (Astro trailingSlash = "never")
[[redirects]]
  from = "/electricity-plans/*/"
  to = "/electricity-plans/:splat"
  status = 301

[[redirects]]
  from = "/texas/*/"
  to = "/texas/:splat"
  status = 301

[[redirects]]
  from = "/admin/*/"
  to = "/admin/:splat"
  status = 301

# Trailing slash removal for faceted navigation
[[redirects]]
  from = "/electricity-plans/*/"
  to = "/electricity-plans/:splat"
  status = 301

# Prevent indexing of internal admin pages
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
