[build]
  publish = "dist"
  command = "npm run build:data && npm install && npx astro build --outDir dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200