/**
 * Auto-generated Provider Mappings from CSV Data
 * Generated: 2025-08-31T03:07:46.575Z
 */

export const PROVIDER_NAME_MAPPING = {
  "frontier utilities": "frontier-utilities",
  "frontier": "frontier-utilities",
  "gexa energy": "gexa-energy",
  "gexa": "gexa-energy",
  "4change energy": "4change-energy",
  "4change": "4change-energy",
  "discount power": "discount-power",
  "discount": "discount-power",
  "cirro energy": "cirro-energy",
  "cirro": "cirro-energy",
  "apge": "apge",
  "rhythm energy": "rhythm-energy",
  "rhythm": "rhythm-energy",
  "atlantex power": "atlantex-power",
  "atlantex": "atlantex-power",
  "just energy": "just-energy",
  "just": "just-energy",
  "tara energy": "tara-energy",
  "tara": "tara-energy",
  "reliant": "reliant",
  "direct energy": "direct-energy",
  "direct": "direct-energy",
  "green mountain": "green-mountain",
  "green": "green-mountain",
  "amigo energy": "amigo-energy",
  "amigo": "amigo-energy",
  "payless power": "payless-power",
  "payless": "payless-power",
  "txu energy": "txu-energy",
  "txu": "txu-energy"
};

export const PROVIDER_COLORS = {
  "frontier-utilities": "#8B5A3C",
  "gexa-energy": "#10B981",
  "4change-energy": "#EF4444",
  "discount-power": "#2563EB",
  "cirro-energy": "#06B6D4",
  "apge": "#DC2626",
  "rhythm-energy": "#FF6B35",
  "atlantex-power": "#7C3AED",
  "just-energy": "#8B5CF6",
  "tara-energy": "#EA580C",
  "reliant": "#E31E24",
  "direct-energy": "#00A651",
  "green-mountain": "#22C55E",
  "amigo-energy": "#F59E0B",
  "payless-power": "#059669",
  "txu-energy": "#1E3A8A"
};

export const PROVIDER_LOGO_URLS = {
  'frontier-utilities': 'https://assets.comparepower.com/images/frontier_utilities.svg',
  'frontier utilities': 'https://assets.comparepower.com/images/frontier_utilities.svg',
  'gexa-energy': 'https://assets.comparepower.com/images/gexa_energy.svg',
  'gexa energy': 'https://assets.comparepower.com/images/gexa_energy.svg',
  '4change-energy': 'https://assets.comparepower.com/images/4change_energy.svg',
  '4change energy': 'https://assets.comparepower.com/images/4change_energy.svg',
  'discount-power': 'https://assets.comparepower.com/images/discount_power.svg',
  'discount power': 'https://assets.comparepower.com/images/discount_power.svg',
  'cirro-energy': 'https://assets.comparepower.com/images/cirro_energy.svg',
  'cirro energy': 'https://assets.comparepower.com/images/cirro_energy.svg',
  'apge': 'https://assets.comparepower.com/images/apge.svg',
  'rhythm-energy': 'https://assets.comparepower.com/images/rhythm_energy.svg',
  'rhythm energy': 'https://assets.comparepower.com/images/rhythm_energy.svg',
  'atlantex-power': 'https://assets.comparepower.com/images/atlantex_power.svg',
  'atlantex power': 'https://assets.comparepower.com/images/atlantex_power.svg',
  'just-energy': 'https://assets.comparepower.com/images/just_energy.svg',
  'just energy': 'https://assets.comparepower.com/images/just_energy.svg',
  'tara-energy': 'https://assets.comparepower.com/images/tara_energy.svg',
  'tara energy': 'https://assets.comparepower.com/images/tara_energy.svg',
  'reliant': 'https://assets.comparepower.com/images/reliant.svg',
  'reliant energy': 'https://assets.comparepower.com/images/reliant.svg',
  'direct-energy': 'https://assets.comparepower.com/images/direct_energy.svg',
  'direct energy': 'https://assets.comparepower.com/images/direct_energy.svg',
  'green-mountain': 'https://assets.comparepower.com/images/green_mountain.svg',
  'green mountain': 'https://assets.comparepower.com/images/green_mountain.svg',
  'green mountain energy': 'https://assets.comparepower.com/images/green_mountain.svg',
  'amigo-energy': 'https://assets.comparepower.com/images/amigo_energy.svg',
  'amigo energy': 'https://assets.comparepower.com/images/amigo_energy.svg',
  'payless-power': 'https://assets.comparepower.com/images/payless_power.svg',
  'payless power': 'https://assets.comparepower.com/images/payless_power.svg',
  'txu-energy': 'https://assets.comparepower.com/images/txu_energy.svg',
  'txu energy': 'https://assets.comparepower.com/images/txu_energy.svg'
};