openapi: 3.0.3
info:
  title: ESID Lookup API
  description: API for retrieving Electric Service Identifiers (ESIDs) from validated addresses
  version: 1.0.0

paths:
  /api/esid/lookup:
    post:
      summary: Retrieve ESID for a validated service address
      description: |
        Looks up the 17-digit ESID (Electric Service Identifier) for a validated address using ERCOT's
        official registry. This operation requires a standardized address from the validation service.
        ESIDs are dynamically generated and never hardcoded per constitutional requirements.
      operationId: lookupESID
      tags:
        - ESID Lookup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
              properties:
                address:
                  $ref: '#/components/schemas/ServiceAddress'
                  description: "Standardized address from validation service"
                planId:
                  type: string
                  pattern: "^[0-9a-fA-F]{24}$"
                  example: "60c72b2f4f1a4c0015e8b123"
                  description: "Selected plan MongoDB ObjectId (for availability checking)"
                sessionId:
                  type: string
                  format: uuid
                  description: "Optional session tracking ID"
                includeHistory:
                  type: boolean
                  default: false
                  description: "Include service connection history"
      responses:
        '200':
          description: ESID lookup completed (may be successful or failed)
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - address
                  - lookupStatus
                properties:
                  success:
                    type: boolean
                    description: "Overall operation success"
                  address:
                    $ref: '#/components/schemas/ServiceAddress'
                    description: "Address used for lookup"
                  esid:
                    type: string
                    pattern: "^[0-9]{17}$"
                    example: "10123456789012345"
                    description: "17-digit ESID (only if found)"
                  lookupStatus:
                    type: string
                    enum: [
                      "FOUND",
                      "NOT_FOUND", 
                      "MULTIPLE_FOUND",
                      "INACTIVE_SERVICE",
                      "NEW_CONSTRUCTION"
                    ]
                    description: "ESID lookup result status"
                  tdspId:
                    type: string
                    example: "oncor"
                    description: "Transmission/Distribution Service Provider"
                  serviceStatus:
                    type: string
                    enum: [
                      "ACTIVE",
                      "INACTIVE",
                      "PENDING",
                      "DISCONNECTED"
                    ]
                    description: "Current service connection status"
                  meterType:
                    type: string
                    enum: [
                      "RESIDENTIAL",
                      "COMMERCIAL", 
                      "INDUSTRIAL"
                    ]
                    description: "Type of electric meter"
                  serviceHistory:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                        event:
                          type: string
                          enum: ["CONNECTED", "DISCONNECTED", "METER_CHANGE"]
                        provider:
                          type: string
                    description: "Service connection history (if requested)"
                  errorMessage:
                    type: string
                    example: "No electric service found at this address"
                    description: "User-friendly error message"
                  suggestedActions:
                    type: array
                    items:
                      type: string
                    example: [
                      "Verify the address with your landlord",
                      "Contact the utility company to establish service"
                    ]
                    description: "Recommended next steps for user"
        '400':
          description: Invalid request (address not validated)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: ERCOT API rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: ERCOT service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ServiceAddress:
      type: object
      required:
        - street
        - city  
        - state
        - zipCode
      properties:
        street:
          type: string
          example: "123 Main Street"
        unit:
          type: string
          example: "Apt 4B"
          nullable: true
        city:
          type: string
          example: "Dallas"
        state:
          type: string
          example: "TX"
        zipCode:
          type: string
          pattern: "^[0-9]{5}$"
          example: "75201"
        zipPlus4:
          type: string
          pattern: "^[0-9]{4}$"
          example: "1234"
          nullable: true
    
    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "ESID_NOT_FOUND"
        message:
          type: string
          example: "No electric service identifier found for this address"
        details:
          type: object
          description: "Additional error context"
        retryAfter:
          type: integer
          description: "Seconds to wait before retry (for rate limiting)"